### PR TITLE
The option to throw exception after logging.error call

### PR DESCRIPTION
**Pull request by shoreward**
You need to call pw.setThrowOnError(True) if you want to use it. And to call pw.setThrowOnError(False) to disable this behavior. This feature is disabled by default.

### CODE REVIEW

**Comment by shoreward** [comment]
Please, check this PR

**Comment by shoreward** [comment]
Hey, say something about it! :)

**Comment by PyWaves** [comment]
Hey @shoreward,

the changes look good. There are small conflicts currently, could you solve those and send another pull request?

Cheers
  Marc

**Comment by nlively** [comment]
@jansenmarc and @shoreward 

I have rebased this branch to `master` and applied the error throwing logic to the additional exceptions handled in the tip of `master`.

https://github.com/PyWaves/PyWaves/pull/40

Please review and merge or respond as you see fit.

Thanks

**Pull request closed without merging**
