### PR TITLE
buy / sell decimal fix

### PR DESCRIPTION
**Pull request by sabotagebeats**
fix calculation for decimals in buy and sell

### CODE REVIEW

**Comment by sabotagebeats** [comment]
tested with blackbot and float prices - works.

**Comment by sabotagebeats** [comment]
tested and seems to work to create float price orders with blackbot properly.

**Comment by CheckRazor** [comment]
I tested this change against USD asset and because USD is 2 decimals this change still provides incorrect price.  Changed the 8 +  to 6 + in address.py to get the correct pricing with amount asset = WAVE and price_asset = USD.

**Comment by sabotagebeats** [comment]
@CheckRazor it should be getting the decimals from the asset and then using those. The 8 i believe is a placeholder for "waves" decimals, which shouldn't be included. I have only tested it with 8 decimal assets though

**Pull request merged**
